import RPi.GPIO as GPIO

R_PIN = 36
G_PIN = 38
B_PIN = 40

GPIO.setmode(GPIO.BOARD)

GPIO.setup(R_PIN, GPIO.OUT)
GPIO.setup(G_PIN, GPIO.OUT)
GPIO.setup(B_PIN, GPIO.OUT)

GPIO.OUTPUT(R_PIN, GPIO.HIGH)
GPIO.OUTPUT(G_PIN, GPIO.HIGH)
GPIO.OUTPUT(B_PIN, GPIO.HIGH)


